### ISSUE TITLE
No such file or directory - /var/lib/puppet/clientbucket

### ISSUE THREAD

**Issue by spuder** [andytinycat/puppet-clientbucket-restore#2]
Thanks for this script. It appears that on puppet version 5.5 that `/var/lib/puppet/clientbucket` is not a valid directory

What versions of puppet is this tested against? 

```
./clientbucket.rb /etc/one/oned.conf
Traceback (most recent call last):
	3: from ./clientbucket.rb:16:in `<main>'
	2: from /usr/lib/ruby/2.5.0/find.rb:43:in `find'
	1: from /usr/lib/ruby/2.5.0/find.rb:43:in `collect!'
/usr/lib/ruby/2.5.0/find.rb:43:in `block in find': No such file or directory - /var/lib/puppet/clientbucket (Errno::ENOENT)
```

**Comment by spuder** [comment]
Looks like there is a fork for newer versions of puppet

https://github.com/rilindo/puppet-clientbucket-restore

For anyone else looking, your clientbucket might be at `/opt/puppetlabs/puppet/cache/clientbucket` (as of puppet 5.5)

```
./clientbucket.rb -t /etc/one/sunstone-server.conf -c /opt/puppetlabs/puppet/cache/clientbucket
```
